name: learnaksara
version: 1.0.0+1
publish_to: none
description: Belajar Akasara
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aksara_logo.png"

flutter:
  assets:
    - assets/images/
  uses-material-design: true

